toml-lang/toml

tests/0.3.0_example.toml
This is what i meant on https://github.com/toml-lang/toml/issues/265
Doing this i figured out that you are able to define the entire language using a TOML file. That would feel like writing a [LANG] compiler in [LANG] language to me! =)
But I'll let you that for you. Hope this one helps.
=> Example with full version coverage

README.md
I've added a reference to my own library for reading TOML files, written in the Nim language (http://nim-lang.org/).
=> Reference to new Nim library added

README.md
=> fix typo of Heka

README.md
Makes these possible. Addresses #295.
```
1_000
5_349_221
1_2_3_4_5     # valid but inadvisable
9_224_617.445_991_228_313
1e4_000_000
```
=> Allow underscores in numbers.

versions/ja/toml-v0.4.0.md
=> Add Japanese translation of v0.4.0.

README.md
- Renamed the section "Oh god, you're right" to "Get Involved"
- The new text indicates that all contributions are welcome
regardless of ones bravery or lack thereof
=> Use friendlier language when asking for contributions

README.md
- Merged the "Seriously?" and "But why?" sections into a single
"Comparison with Other Formats" section.
- Added paragraphs about JSON, INI, and YAML
=> Contrast TOML to JSON, INI, and YAML in the README

README.md
Homepage: <https://github.com/jakwings/toml-j0.4>
Demo: <https://jakwings.github.io/toml-j0.4/>
Thanks you! :gift:
=> Add another v0.4.0 compliant parser in JavaScript.

README.md
EDIT: Are you busy all day? I'll send a reminder a week later. ;-)
=> Add a v0.4.0 compliant encoder to the list

README.md
Implementation based on @skystrife's excellent C++11 parser
=> Add the v0.4.0 compliant parser for the R language

README.md
I think that having an index might be useful, it certainly is for me.
This is the code I used to generate it, idk if it's worth to commit it somewhere:
```javascript
$('article.markdown-body').find('h2').map(function(i, v){
return ("[" + $(v).text().trim() + "]" + "(#" + $(v).find('a').attr('id') + ")");
}).toArray().join("\n- ")
```
=> This README needs an index yo!

README.md
=> Clarify that comments are OK in multiline arrays

README.md
My project "MCPhoton" uses TOML for its configuration files.
=> Add a project that uses TOML

README.md
=> GitLab CI Multi Runner in README.md list

versions/cn/toml-v0.4.0.md
Add Chinese translation of v0.4.0
=> add Chinese translation of v0.4.0

versions/ko/toml-v0.4.0.md
=> Add korean translation of v0.4.0

README.md
This makes searching it easier
=> Add the word trailing to the readme

README.md
Traefik is quite active and modern HTTP proxy using TOML.
https://github.com/containous/traefik
https://traefik.io
=> Add a project using TOML

README.md
=> Clarify certain things about strings

README.md
Add example for dotted key in inline table for consistency.
=> Update inline table example with dotted keys

toml.abnf
=> Disallow ASCII delete in Literal strings

README.md
CF: https://github.com/toml-lang/toml/issues/499#issuecomment-388241800
=> Move instructions on naming restrictions to Keys section

README.md
#505 wasn't super comprehensive with that.
=> Remove incorrect/redundant statements

toml.abnf
=> Remove forward-slash (solidus) from valid escape character sequences.

README.md
=> Add cautionary note regarding floats as dotted keys

CHANGELOG.md
=> Add news entry for heterogenous array values

README.md
=> Use longer names in examples

README.md
=> Clarify when array of tables ends

README.md
... since the definition reads strangely otherwise.
Follow-up PR to #680.
=> Switch sentence order in array of tables definition

README.md
@pradyunsg If you're ok with it, I'd like to add your name to the byline of the spec. This also acknowledges that many others have given time and effort in the creation of today's TOML spec.
=> Add Pradyun, et al.

README.md
=> Clarify that line-ending backslashes are unescaped

toml.md
=> Add another example of integer grouping

toml.md
=> Key forms are equivalent + reflow the "warnings about keys" bits

toml.md
=> Array of tables phrasing changes

toml.md
=> Clarify what "quotation marks" means

CHANGELOG.md, docs/README.md, scripts/release.py
I *definitely* didn't overengineer this.
=> New release process

CHANGELOG.md
Should be the last thing needed for #750.
=> Add changelog entries for recent changes

scripts/release.py, toml.abnf, toml.md
=> Add ANBF to release artifacts

scripts/release.py
Basically for solving https://github.com/toml-lang/toml.io/pull/23#pullrequestreview-492206132.
=> Minor updates to the release automation

toml.abnf, toml.md
Would be good to use secure urls for the documentation links.
=> docs: use secure urls

toml.md
Reopening https://github.com/toml-lang/toml/pull/838 now that https://github.com/toml-lang/toml/issues/837 was rejected.
=> Clarify that CR not followed by LF is not allowed in an MLB
