toml-lang/toml

README.md
Code points was not precise enough.
Explicitly disallow the JSON UTF-16 surrogate hack which would cause portability issues.
(Something Python 3 should have done, incidentally; as of Python 3.4 you can build UCS-2 strings that can't be printed to a UTF-8 stream)
=> Unicode escapes must be scalar values

README.md
After reflecting on the matter of key names for quite a while, and taking into consideration the many opinions in #65, #67, #220, etc, I've changed my mind on how I think they should be specified. This PR proposes two types of keys: bare and quoted. Bare keys are extremely restrictive `[A-Za-z0-9-_]+` while quoted strings can contain almost anything. I like this approach because it is easy to understand (and remember) and guides users to choose simple key names while still making complex names possible. This proposal should also make the parser's job very simple and eliminate any weirdness that could come from having to deal with undelimited Unicode.
cc @wycats, @BurntSushi, @ChristianSi
=> Clarify key name syntax.

README.md
There is no reason to allow escaping of slashes, since that character can appear unescaped. I only allowed this because I was trying to be the same as JSON's string definition (to make it easy to implement TOML parsers by reusing JSON string parsing), but since 1a11392094c8b1376f9e406324c82e248d140ad4 that hasn't been true anyway. And, in retrospect, being JSON compliant there won't get you much anyway.
I'd like to hit 1.0 soon, and now's the time to remove anything that no longer makes sense given the real world experience we've all had with TOML.
=> Remove slash as an escapable character.

README.md
Added link to parser/encoder [toml.dart](https://github.com/just95/toml.dart) and [yaml2toml.dart](https://github.com/just95/yaml2toml.dart) converter.
=> Add link to Dart implementation.

README.md
Concrete proposal for the inline table syntax I first proposed in Issue #219. Here's a quick taste:
```
name = { first = "Tom", last = "Preston-Werner" }
point = { x = 1, y = 2 }
address = { proto = "http", ip = "10.0.0.1", port = 8080 }
points = [ { x = 1, y = 2, z = 3 },
{ x = 7, y = 8, z = 9 },
{ x = 2, y = 4, z = 8 } ]
```
This is about as brief as I could think to make it, so if there are specific issues that need clarifying, please bring them up.
=> Add inline table syntax.

README.md
Fix a typo in `README` / Projects using TOML.
=> Fix typo in README: "langage" -> "language"

README.md
The latest version of cpptoml has been updated to support v0.4.0's features.
Thanks!
=> Move cpptoml parser compliance to v0.4.0 group.

README.md
The latest version of `toml-rb` has been updated to support v0.4.0's features.
=> Move `toml-rb` parser compliance to v0.4.0 group.

README.md
MeTA uses TOML for all of its configuration. More info on functionality is [on our website](https://meta-toolkit.github.io/meta/).
A few examples of how we use TOML: [specifying text tokenization pipelines](https://meta-toolkit.github.io/meta/analyzers-filters-tutorial.html), [specifying classifiers](https://meta-toolkit.github.io/meta/classify-tutorial.html), [a complete configuration file](https://github.com/meta-toolkit/meta/blob/develop/config.toml) that contains setup for datasets, etc.
=> Add MeTA to TOML-using projects.

README.md
v2.2.0 of the toml npm package now supports v0.4.0 of the spec and is tested in Node, io.js, and the browser
=> Move toml npm package to v0.4.0 section

README.md
The latest version of the PHP Toml parser has been updated to support v0.4.0's features.
Thanks!
=> Move PHP Toml parser to compliance v0.4.0 group.

README.md
- Removed some extraneous words and phrases ("Boom", "Why not?", "Hear
me roar", etc.)
- Removed some informal language ("TOML don't care")
- Changed the example value "Lance Uppercut" to use the name of TOML's
creator
=> Use more formal language in the TOML examples

README.md
Here is another Ruby parser supporting the 0.4.0 version of the spec. It's using [Racc](https://github.com/tenderlove/racc).
Thanks!
=> Add another Ruby parser

README.md
I totally missed on the fact that plain integers can be used as bare keys when writing my parser. This actually might make two-phase parsing (i.e. lexing then parsing) an unfavorable approach since there is an ambiguity on whether `1234` is a key or a number. It's therefore good to notice in advance, hence this clarification.
=> Clarify on the use of bare integers as keys.

README.md
[Config::TOML](https://github.com/atweiden/config-toml) is a v0.4.0 compliant parser.
=> Add v0.4.0 compliant parser for Perl 6

README.md
i have written an implementation for toml in scala for pre-v0.1.0 version.
=> listed toml-scala in pre-v0.1.0 implementations

README.md
This allows three kinds of datetimes:
```bash
1979-05-27T07:32:00Z
1979-05-27T00:32:00-07:00
1979-05-27T00:32:00.999999-07:00
1979-05-27T07:32:00
1979-05-27T00:32:00.999999
1979-05-27
```
See #263 for why this is being proposed.
=> Allow less specific datetimes.

README.md
This PR adds [LolToml](https://github.com/andrusha97/loltoml), a v0.4.0 compliant parser for C++11.
=> Add another implementation to the readme

README.md
There already was an example showing it's legal, so it isn't strictly necessary, but there was one for different kinds of strings as well. Also changes "string types should be considered a single type" to avoid overloading "type".
=> Allow arrays of arrays of different types even more explicitly.

README.md
TOML.pm uses TOML::Parser, and TOML::Parser supports v0.4.0.
=> updated v0.4.0 compliant libraries

README.md
This project is actively tracking 0.4.x; I haven't tested to ensure that it is actually passing all 0.4.0 tests, but it does claim to be tracking 0.4.0, so the readme might need a check on this one.
Paging @uiri to chime in on this.
=> Uiri/toml moved to 0.4.0

README.md
As discussed in https://github.com/toml-lang/toml/issues/49.
It would be nice to avoid a `.yaml`-vs-`.yml`-style debate in the future.
=> specify the .toml extension

README.md
It makes sense for all implementations to support millisecond precision for datetimes. This also removes the suggestion of a warning, as that opens up a whole new can of worms. Every implementation may provide warnings on anything it wishes without the spec weighing in on the matter.
=> Add millisecond precision expectation to datetime.

README.md
This clarifies the definition of "quoted keys" in the section about tables to
indicate that keys can either be basic strings (surrounded by double quotes) or
literal strings (surrounded by single quotes).
Closes #354
=> Clarify that literal strings can be table keys

README.md
Compare to other implementations for Go:
- [BurntSushi/toml](https://github.com/BurntSushi/toml) It supports v0.4.0
- [naoina/toml](https://github.com/naoina/toml) Fewer bugs, hopefully. In [my fork of naoina/toml](https://github.com/kezhuw/naoina-toml/commits/master), I fixes two of them, but not got merged yet.
- [pelletier/go-toml](https://github.com/pelletier/go-toml) It uses reflection.
So, it is a v0.4.0 compliant TOML implementation, written using reflection in Go.
=> Add new v0.4.0 compliant implementation in Go

README.md
This separates out the definition of key/value pairs from the table definition and moves it to the top of the spec. I think this order makes more sense, defines the primary building block of TOML early on, and shortens and simplifies the table definition.
=> Define key/value pairs up top. Closes #348.

README.md
I've just released the first working (stable) release of [my TOML library](https://github.com/TheElectronWill/TOML-javalib), therefore I add it there.
=> Add TOML-javalib to the list of implementations

README.md
It even runs the BurntSushi-testsuite as part of its tests.
=> htoml now 0.4.0 compliant

README.md
This is a possible solution for the concerns raised in #362. I'd like to have a conversation around a concrete spec. I have to say that this turns out not to feel too complex for me, and solves almost every issue that has been brought up.
The bit about how to handle conversion from LocalDateTime when the interpreted instant would either not exist, or exist twice, leads to ambiguity, but I phrased it as such to simplify parser construction. Most languages will have some built-in approach to resolving the instant, but I assume they will differ slightly, and over-specifying the TOML spec could make the parsing a nightmare. I figure that if this kind of ambiguity is unacceptable to a user, they can simply use an OffsetDateTime. I'm curious to hear thoughts on the matter.
=> Specify OffsetDateTime, LocalDateTime, LocalDate, and LocalTime types.

tests/fruit.toml, tests/fruit.yaml
By my reading, this should be valid, and `tomlv` accepts it:
```
$ tomlv -types fruit.toml                                                                                                                         ~
fruit.blah                         ArrayHash
fruit.blah.name                String
fruit.blah.physical            Hash
fruit.blah.physical.color  String
fruit.blah.physical.shape  String
fruit.blah                         ArrayHash
fruit.blah.name                String
fruit.blah.physical            Hash
fruit.blah.physical.color  String
fruit.blah.physical.shape  String
```
However, I am proposing it as a new test because htoml _doesn't_ accept this (https://github.com/cies/htoml/issues/16), so I want to clarify the issue.
=> Add test for nesting within arrays of tables

toml.abnf
One of the most important things we'll need for the TOML 1.0 release is a proper grammar. I've worked one up here as a starting point. I chose RFC 4234 ABNF because it feels much more modern and suitable for a Unicode world than ISO EBNF. Also, JSON uses ABNF and so many people should already be familiar with it.
This grammar should be complete. It also includes scientific notation for floats, as I expect those will go in soon.
I'm certainly no ABNF expert, and I'd love any suggestions for making this grammar more readable.
=> Add ABNF description of TOML.

README.md, toml.abnf
This change allows (presumably accidental) whitespace to exist in multi-line basic strings between a line-ending backslash and the following newline. See #436 for more context.
=> Allow accidental whitespace between backslash and newline.

README.md
What
===
Add clarification that bare keys are always strings, even if they are
only digits.
Why
===
While it's implied that keys are all the same type and are of the string
type, it's not explicit in the specification. In some libraries using
the specification it's been suggested that bare keys could be
interpreted as other types, e.g. integers, but this is problematic as
most languages cannot effectively handle mixed type keys on maps. We
should be explicit that keys are only strings.
Ref: BurntSushi/toml#154
=> Clarify that keys are always strings.

README.md
tomlc99 is a TOML C library that is v0.4.0 compliant.
=> Add link to a C impl

README.md
I know I've already done a TOML library (Toml-javalib) but NightConfig is a more general (and more powerful) configuration library that supports TOML and other formats.
=> Add a new Java implementation: NightConfig

README.md
Yet another node.js/io.js/browser implementation.
(Why is the runtime being listed instead of the language, for javascript? this new implementation is actually written in typescript, a superset of javascript)
=> Adding a new node.js/io.js/browser implementation

README.md
As a user
I should be able to search for "JavaScript"
to find JavaScript implementations.
This is more consistent because other entries are languages while Node.js is not a language.  This grew a little complicated because transpiled languages are still useful to a user searching for "JavaScript" so I listed then under JavaScript but also indicated the authored language.
=> Mark JavaScript implementations as JavaScript

README.md, toml.abnf
Closes #487
Closes #458
Closes #448
This is a modification to allow an arbitrary number of comments and newline in multiline arrays, instead of a fairly inconsistent format as currently specified.
=> Allow multiple newlines and comments in multiline arrays

README.md, toml.abnf
Fixes #485 
Fixes #464
Closes #472 
Closes #458
Closes #484
I've made a first pass on the ABNF and README. I think this is close to complete.
Obviously, I'm open to comments and suggestions. :)
=> Sync ABNF and Specification

README.md
By moving the community listings to the wiki in 4cfea10, some links in the table of contents got corrupted. 
I removed the links to the sections that have been moved and added a link to the new section of the README about the wiki.
=> Add link to wiki section to table of contents.

CHANGELOG.md, README.md, toml.abnf
Closes #389.
This adds support for non-finite float values (`-inf`, `inf`, `+inf`, `nan`) and clarifies that signed zeros (integer and float) are valid and what they mean.
=> Add non-finite floats and clarify signed zeros

CHANGELOG.md, README.md, toml.abnf
Closes #409.
```
hex1 = 0xDEADBEEF
hex2 = 0xdeadbeef
hex3 = 0xdead_beef
oct1 = 0o01234567
oct2 = 0o755 # useful for Unix file permissions
bin1 = 0b11010110
```
=> Add hex, octal, and binary integer formats

README.md, toml.abnf
Closes #499
This will probably conflict with #500 since this also adds a "Keys" section.
=> Dotted keys

toml.abnf
=> Remove 127 as a control character in ML strings

toml.abnf
Not 100 % sure but I don't see a reason not to use optional directly in the 'inline-table' definition.
=> Simplify inline-table ABNF definition

README.md
=> Clarify that float integer parts are decimal digits only

README.md
Since all the other contents have links, I thought that it would be good to add `MIME Type`. Thanks!
=> Add `MIME Type` to table of contents

versions/cn/toml-v0.5.0.md
No change for content.
There was one space lacked between words.
=> Repair space between words

README.md
According to `.abnf` and reason. (Although I don't understand why hex/oct/bin could not used for negative.)
=> Clarify that leading `+` is not allowed for x/o/b

CHANGELOG.md, toml.abnf
This is more a suggestion than a request.
I noticed that the current ABNF grammar allows [UTF-16 surrogate code points](https://unicode.org/glossary/#surrogate_code_point) (0xD800 - 0xDFFF) in strings and comments. This seems inconsistent, because it is invalid to insert these code points via escape sequences (e.g. \uD800).
This commit excludes the surrogate range. Because this affects five separate rules, I added a reusable rule `non-ascii`, to reduce redundancy.
=> Do not allow surrogate code points in ABNF

README.md
A hash symbol should **not** mark the rest of the line as a comment if it is inside a string.
=> Be explicit about the use of # inside strings

README.md
Hi! First time around here, but I saw an open request for a PRs.
I believe this answers the request in Issue #422 (marked as a desirable on the 1.0 roadmap) with an explanation of how TOML compares to other formats for data interchange. In order to keep the documentation minimally sized I also compressed the discussion of TOML vs YAML vs JSON into a single paragraph.
Paragraph on INI files got amended slightly to point more directly at the comparisons that have been made. I also removed assertions of it being a file format because by definition, a format adheres to a standard, and README.md asserts INI is not a standard. It shouldn't affect overall meaning, however.
Linking other references seemed like good academics and an extension of the already existing plan.
My paragraph on the …
=> Improve TOML's "Comparison with Other Formats" section

README.md
It wasn't fully clear from the specs whether or not it is allowed to
create a table [a] explicitly when earlier on in the TOML document the
table [a.b] was created, since that expression creates [a] implicitly.
See: https://github.com/toml-lang/toml/issues/638
=> Clarify the use of [a] after [a.b]

README.md
It wasn't fully clear from the specs whether or not it is allowed
to have multiple Key/Value pairs together on 1 line of a TOML doc.
See: https://github.com/toml-lang/toml/issues/637
=> Clarify that multiple key/vals on 1 line are invalid

CHANGELOG.md, README.md, toml.abnf
In response to #571, these changes permit the horizontal tab character to be used in both basic strings and multi-line basic strings.
=> Re #571, allow raw tabs in basic and MLB strings

CHANGELOG.md, README.md
Closes #630 
(maybe?) Supercedes and closes #647.
---
This was a draft I had locally that I just updated to use "cannot be added to them" borrowed from #647.
=> Immutable Inline tables

README.md
=> Add advice to not define dotted keys out-of-order

CHANGELOG.md, README.md, toml.abnf
Per #356, this PR allows for leading zeroes on the integer parts of exponents in floats.
=> Permit leading zeroes in exponent parts of floats

CHANGELOG.md, README.md
Closes #631 
(maybe?) Supersedes and closes #654
=> Clarify behavior of tables defined implicitly by dotted keys

README.md
"Similarly" and "as well" don't fit the local context. Closes #659.
=> Cleanup sentence on out-of-order definitions of tables

toml.abnf
In hope that this will make reading the ABNF easier and the implementation simpler, the keyval can be deduplicated: it is in both plain root-level key-value and in inline-table's key-value, yet the content is exactly the same.
=> Deduplicate a rule in ABNF

README.md
* Explicitly mention that table arrays can have regular subtables.
* Document that children of table arrays must not be defined above their parents (with example).
* Document that attempts to redefine a normal table as an array must produce a parse-time error (with example).
Closes #658.
=> Explain ordering of subtables under arrays of tables

README.md
=> Allow heterogeneous arrays

README.md
This is a spin-off of #664. It makes it explicit in the written spec that arrays of tables can contain regular (non-array) subtables which belong to the most recently defined table element above them.
@pradyunsg considered this unnecessary, arguing that "this is self-evident from the example JSON below". However, I would object that the examples should *not* introduce additional features, they should only *exemplify* what's already mentioned in the text.
Additionally, this particular example is currently a bit hard to understand since the text above it only talks about "double-bracketed sub-tables" (nested arrays of tables), making it surprising to also find a single-bracketed sub-table there (in fact, I initially overlooked it totally, instead just seeing what I had been told I would …
=> Explicitly mention that arrays of tables can contain subtables

toml.abnf
this:
```
string = """ escaped \
end"""
```
Was parsed as a single escaped newline, then as a newline part of the
string itself.
While it is fitting the role of rejecting invalid input and accepting
the valid one, it did not fit the role of parsing the content into
tokens.
To help the implementation, a multiline whitespace/newline token is
introduced: escaped-ws-nl
This fixes #669.
=> Make the ABNF syntax tree, more semantic for ml-basic-string

README.md
The old list only mentions the obsolete Datetime time instead of the four
date/time types we have today. Backlinks to each type are added as well.
This rescues a change from the abandoned PR #663, authored by @eksortso.
Ping @eksortso, @pradyunsg . Please review and merge.
=> Improve type list in key/value pairs section

CHANGELOG.md, README.md
=> Clarify that trailing commas are not allowed in inline tables

CHANGELOG.md, README.md
=> Clarify that control characters are not permitted in comments

CHANGELOG.md, README.md, toml.abnf
This addresses the ambiguity in #640 in how quotation marks are parsed in multiline basic strings. It also addresses the same matter in multiline literal strings.
=> Correct use of quotation marks in multiline strings

README.md
Per a conversation regarding point 9 of #701, this PR annotates two examples with comments to show how you can write to unused names, and to show why reusing a name as a table when it originally wasn't is invalid.
=> Clarify example showing how to add new keys

CHANGELOG.md, README.md, versions/en/toml-v1.0.0-rc.1.md
Closes #698 
(note to self: squash-merge this one)
=> Release 1.0.0-rc.1

docs/README.md
For starters, this documents our release process.
Soon, there will be significant restructuring of the contents of this repository, and keeping this documentation updated would help during that migration.
=> Add maintainance documentation

README.md, versions/en/toml-v0.5.0.md
from #723 
1. https://github.com/toml-lang/toml/blame/master/README.md#L795 has two spaces after period.
2. https://github.com/toml-lang/toml/blame/master/README.md#L794 the space after key/value is \xA0, not \x20.
3. https://github.com/toml-lang/toml/blame/master/README.md#L945 or of compatible type should be removed, because now mixed type array is ok.
I found these when I was translating docs word by word. Since it's rc version now, fixing them do more good than harm.
---
for #725 
Make it clear in example, that multiline literal string can also end with (single) quote less than three, like multiline basic string do now.
---
#722
=> fix some pretty small problem

README.md
* Break lines that are too long
* Clarify that EOF is allowed after key/value pair
* Fix grammar oddity
* Better explain what the "expected" integer range means
* Add a few hyphens
* Turn internal crossreference into hyperlink
* Avoid duplicate "expressed"
=> Polish up the README

README.md
* Replace the vague term "expected" with the RFC 2119-compatible terms "should", "must", "required"
* Clarify that an error must be thrown if an integer cannot be represented losslessly
Fixes #736.
=> Replace "expected" by more precise terms

toml.md
Clarifies 'floats' section to explicitly demonstrate that omission of integer or fractional+exponent parts isn't legal (closes #759).
=> Add invalid float examples

CHANGELOG.md, toml.abnf, toml.md
Per #766 this change updates the specification to allow comments with newlines before commas in arrays. Modifies toml.md, toml.abnf, and CHANGELOG.md.
=> Allow comments w/ newlines before commas in arrays

CHANGELOG.md, toml.md
During discussion [in issue 744](https://github.com/toml-lang/toml/issues/744#issuecomment-706912461) and elsewhere, users coming from Python with no experience with INI file formats were confused by the presence of indentation in a few of the examples in `toml.md`. Indentation is essentially whitespace (except inside strings) and is discouraged before keys and table headers, but this wasn't being stated clearly.
This PR makes these facts clear about indentation. For keys and table headers in examples, all indentation was stripped, and indentation is clearly treated as whitespace and its use is discouraged. For consistency, similar language was applied to array values, though indentation was preserved and it isn't discouraged there. A few minor grammar corrections were also made.
=> Clarify indentation usage and remove indents from table examples

CHANGELOG.md, toml.md
This PR contains a paragraph and new example in the Table section of `toml.md` that explicitly describes the top-level table. The text and the example makes it clear that this table is nameless and cannot be relocated.
=> Clarify and describe the top-level table

toml.md
This PR changes the names given to arrays of tables in the examples to make them plural. This is primarily an aesthetic fix, so the changelog is not modified. Fixes #782.
=> Modify examples to give plural names to arrays of tables

toml.abnf
Although lowercase is not technically wrong, this document uses
uppercase hex digit in majority. So make that consistent.
=> ABNF: Use uppercase hex digit consistently

CHANGELOG.md, toml.md
This PR clarifies how tables are created and defined within a TOML document, in order to make the rules for definition more consistent. Also makes minor grammar corrections and example tweaks.
Closes #795.
=> Clarify how tables are created and defined

toml.abnf
The spec states that, for both multiline basic and literal strings:
> A newline immediately following the opening delimiter will be trimmed.
This is currently not reflected in the ABNF definition, using basic
string as an example:
```abnf
ml-basic-string = ml-basic-string-delim ml-basic-body ml-basic-string-delim
ml-basic-string-delim = 3quotation-mark
ml-basic-body = *mlb-content *( mlb-quotes 1*mlb-content ) [ mlb-quotes ]
```
Implemented directly (or via an ABNF parser generator), the initial new line 
sequence after `"""` will be part of `ml-basic-body`. This is misleading.
IMHO, this special newline should have its own place in the ABNF syntax.
Hence this patch.
=> ABNF: Reflect first newline in multiline string explicitly

README.md
It doesn't make sense to have the same port `8001` appear twice in the array. I've updated the README with the `ports` array to be `[ 8000, 8001, 8002 ]`, presumably as it was originally intended.
For more on this topic, please see the conversation in https://github.com/toml-lang/toml.io/pull/37.
=> Update ports in README

toml.abnf
The spec says:
> Control characters other than tab (U+0000 to U+0008, U+000A to U+001F, U+007F) are not permitted in comments.
non-eol did not exclude 7F (DEL) properly.
=> Correct ABNF to prohibit DEL in comments

toml.md
There have been two cases recently where I had someone who was confused
about this.
This clarifies that multi-line strings are not allowed as key names for
the casual reader; the phrases "basic string" and "literal string" have
a specific meaning in the TOML spec, but that's not really obvious if
you're just looking up "what is the valid syntax for a key?" as the
rules are explained in a different section, and it requires some careful
reading.
=> Clarify that multi-line strings are not allowed in key names

CHANGELOG.md, toml.md
Removes and replaces language that could potentially allow dotted keys in a parent table of an existing table to inject key/value pairs into subtables of the existing table. Closes #846.
This PR replaces the previous PR #848.
=> Clarify where and how dotted keys define tables

.gitattributes, toml.abnf
…  add .gitattributes so CRLF is added at checkout.  
Fixes issue #873 .  
Although the diff looks like the only change is the one added comment paragraph about UTF-8,  
the .gitattributes will convert the LFs to CRLFs.
=> Force CRLF line endings in toml.abnf

CHANGELOG.md, toml.abnf, toml.md
This adds a shorthand for the escape character `\e` (0x1B).
This is useful especially when talking about things like terminal escape
sequences, which use this character regularly.
Fixes #715.
=> Add shorthand for escape character

CHANGELOG.md
The `\e` PR, #790, was made before v1.0.0 was released, so the change it makes to CHANGELOG put the change note in the wrong place.
=> Fix `\e` CHANGELOG note being in the wrong place

CHANGELOG.md, toml.abnf, toml.md
Allows the seconds portion of values with Offset Date-Time, Local Date-Time, and Local Time type to be omitted. Closes #671.
This PR replaces the older PR #696, which was written pre-v1.0.0. The exact same changes to the text in the specification and the ABNF appear in both PR's.
=> Make seconds optional in Date-Time and Time

CHANGELOG.md, toml.md
Closes https://github.com/toml-lang/toml/issues/835
=> Allow newline normalization in multi-line literal strings

toml.md
UTF-8 is an encoding, not a character set, so "UTF-8 character" is not correct.
I picked the "should be implemented as" wording from floats, but am not sure this is what you want. It feels like there should be some consistent way to say "TOML interpreters should output $type as $format" for strings, integers, and floats (and maybe others...).
=> Replace "UTF-8 characters" with "Unicode characters"

toml.md
This PR is an outcome of https://github.com/toml-lang/toml/discussions/932. Right now the spec only uses the "plural" naming conventions in its array-of-tables examples. However, it is far from clear that this is the only legitimate convention in such cases. Consider as example:
```toml
[[planets]]
name = "Mercury"
aphelion = 0.466697
radius = 2440
[[planets]]
name = "Venus"
aphelion = 0.728213
radius = 6052
```
This might seem unintuitive and perhaps even confusing to the reader or editor of the TOML file, since each ``[[...]]`` section header is only followed by a *single* instance of the described item (a planet, in this case). This can be made clearer by using the "singular" naming convention instead, and prominent TOML users such as …
=> Make spec neutral regarding array-of-table naming style

CHANGELOG.md, toml.abnf, toml.md
In reconsideration of the limitation of control codes within comments discussed in #567, a case was made to simplify comment parsing. This PR intends to replace those previously imposed restrictions with a simplified approach that permits anything except newlines.
=> Permit more control characters in comments

CHANGELOG.md, toml.md
This PR applies the changes to clarify Unicode and UTF-8 references, done originally for #924 while considering relaxations on control code in comments. These are standalone changes, separate from the original scope of #924. Many thanks to @abelbraaksma and @ChristianSi for their work on this.
=> Clarify Unicode and UTF-8 references

toml.md
This corrects an instance of the wrong terminology being used to describe the nature of multi-line literal strings. The original author wrote "raw strings" in the example, but TOML doesn't have "raw" strings, but rather, "literal" strings.
=> Change wording for literal string in example

toml.abnf
I suppose that the `6e` here should be capitalized like other unicodes in the file.
This change unifies the file without affecting any of the syntax.
=> Capitalize the unicodes in `toml.abnf`

CHANGELOG.md, toml.md
In the discussion on #603, it became clear that no restrictions are placed on parsers that could further modify the hash tables that they generate based on included comments. The purpose of this PR is to assure that parsers will never modify a TOML document's resulting hash table due to the presence or contents of the comments contained within the document.
The change to `toml.md` will prevent a certain class of abuses of the TOML syntax, without prohibiting comment-preserving parsers from doing their thing (as those comments are not part of the resulting table but merely reference it from locations in the source document).
(This PR replaces #948.)
=> Clarify that comments never affect the tables produced by parsers

toml.md
Kind-of obvious, but doesn't hurt to explicitly mention it, as it adds just one word. Rephrased slightly for clarity.
Fixes #1027
=> Explicitly mention arrays are ordered

toml.md
"Millisecond precision is required" could be interpreted as a requirement for input to be valid TOML. This commit adds examples of valid TOML time values that uses tens of second to remove the ambiguity.
Refs: https://github.com/alexcrichton/toml-rs/pull/416
Co-Authored-By: Dave Ostroske <eksortso@users.noreply.github.com>
=> Clarify sub-millisecond precision is allowed

CHANGELOG.md, toml.abnf, toml.md
This reverts commit ab7495887ccd0f567d8a220e1a5ab0ca6fdbd16f.
I'm a simple guy. Someone reports a problem, I drink coffee and fix it. No one reports a problem? There is nothing to fix and I go drink beer.
No one really reported this as a problem, but it *does* introduce needless churn for all TOML implementations and the test suite. Do we need to forbid *anything* in comments? Probably not, and in strings we probably only need to forbid \x00. But at least before it was consistent with strings, and more importantly, what everyone wrote code for, which is tested, and already works.
[None of the hypotheticals](https://github.com/toml-lang/toml/issues/567#issuecomment-568269120) on why this is "needed" are practical issues people reported, and most aren't even fixed: a comment can still …
=> Revert "Permit more control characters in comments (#924)"

CHANGELOG.md
One of my difficulties in updating TOML implementations in the past was figuring out what exactly I need to change, as the changelog has typically been extremely concise.
This expands things with commit references and some examples for changes in syntax, which should make things a lot easier for people looking to update TOML 1.0 implementations.
=> Expand changelog
